name: Run Selenium WebDriver Tests

on:
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'   # Use Eclipse Temurin (OpenJDK)
          java-version: '23'        # Specify Java version 23

      - name: Verify Java version
        run: java -version

      - name: Set up Maven
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Chrome Setup
      - uses: browser-actions/setup-chrome@latest

      - name: Build with Maven
        run: mvn clean install
